<?php

return [
    'plans' => [
        [
            'id' => 'barokah-3',
            'name' => 'Barokah',
            'duration_months' => 3,
            'price' => 750000,
            'formatted_price' => 'Rp 750.000',
            'period' => 'per 3 bulan',
            'is_featured' => false,
            'max_santri' => null,
            'max_users' => null,
            'description' => 'Fitur lengkap manajemen pesantren tanpa integrasi payment gateway.',
            'features' => [
                ['name' => 'Data Santri (Unlimited)', 'included' => true],
                ['name' => 'Keuangan SPP & Tabungan', 'included' => true],
                ['name' => 'Laporan Keuangan', 'included' => true],
                ['name' => 'Akademik & Rapot', 'included' => true],
                ['name' => 'Kalender & Agenda', 'included' => true],
                ['name' => 'Notifikasi WhatsApp Manual', 'included' => true],
                ['name' => 'Invoice WhatsApp Otomatis', 'included' => false],
                ['name' => 'Broadcast Tagihan Bulanan (WA)', 'included' => false],
                ['name' => 'Syahriah Payment Gateway (VA)', 'included' => false],
                ['name' => 'Kartu Syahriah Digital (VA)', 'included' => false],
            ],
            'button_text' => 'Pilih Paket',
            'button_class' => 'btn-outline',
        ],
        [
            'id' => 'barokah-6',
            'name' => 'Barokah',
            'duration_months' => 6,
            'price' => 1500000,
            'formatted_price' => 'Rp 1.500.000',
            'period' => 'per 6 bulan',
            'is_featured' => false,
            'max_santri' => null,
            'max_users' => null,
            'description' => 'Fitur lengkap manajemen pesantren tanpa integrasi payment gateway.',
            'features' => [
                ['name' => 'Data Santri (Unlimited)', 'included' => true],
                ['name' => 'Keuangan SPP & Tabungan', 'included' => true],
                ['name' => 'Laporan Keuangan', 'included' => true],
                ['name' => 'Akademik & Rapot', 'included' => true],
                ['name' => 'Kalender & Agenda', 'included' => true],
                ['name' => 'Notifikasi WhatsApp Manual', 'included' => true],
                ['name' => 'Invoice WhatsApp Otomatis', 'included' => false],
                ['name' => 'Broadcast Tagihan Bulanan (WA)', 'included' => false],
                ['name' => 'Syahriah Payment Gateway (VA)', 'included' => false],
                ['name' => 'Kartu Syahriah Digital (VA)', 'included' => false],
            ],
            'button_text' => 'Pilih Paket',
            'button_class' => 'btn-outline',
        ],
        [
            'id' => 'muharam-3',
            'name' => 'Muharram',
            'duration_months' => 3,
            'price' => 1500000,
            'formatted_price' => 'Rp 1.500.000',
            'period' => 'per 3 bulan',
            'is_featured' => false,
            'max_santri' => null,
            'max_users' => null,
            'description' => 'Solusi lengkap dengan otomasi payment gateway & WhatsApp broadcast.',
            'features' => [
                ['name' => 'Semua Fitur Barokah', 'included' => true],
                ['name' => 'Invoice WhatsApp Otomatis', 'included' => true],
                ['name' => 'Broadcast Tagihan Bulanan (WA)', 'included' => true],
                ['name' => 'Syahriah Payment Gateway (VA)', 'included' => true],
                ['name' => 'Kartu Syahriah Digital (VA)', 'included' => true],
                ['name' => 'Pencairan Saldo Otomatis', 'included' => true],
                ['name' => 'Prioritas Support', 'included' => true],
            ],
            'button_text' => 'Pilih Muharram',
            'button_class' => 'btn-primary',
        ],
        [
            'id' => 'muharam-6',
            'name' => 'Muharram',
            'duration_months' => 6,
            'price' => 3000000,
            'formatted_price' => 'Rp 3.000.000',
            'period' => 'per 6 bulan',
            'is_featured' => true,
            'max_santri' => null,
            'max_users' => null,
            'description' => 'Solusi lengkap dengan otomasi payment gateway & WhatsApp broadcast.',
            'features' => [
                ['name' => 'Semua Fitur Barokah', 'included' => true],
                ['name' => 'Invoice WhatsApp Otomatis', 'included' => true],
                ['name' => 'Broadcast Tagihan Bulanan (WA)', 'included' => true],
                ['name' => 'Syahriah Payment Gateway (VA)', 'included' => true],
                ['name' => 'Kartu Syahriah Digital (VA)', 'included' => true],
                ['name' => 'Pencairan Saldo Otomatis', 'included' => true],
                ['name' => 'Prioritas Support', 'included' => true],
            ],
            'button_text' => 'Pilih Muharram',
            'button_class' => 'btn-primary',
        ]
    ]
];
